namespace: elk

stack:
  defines: process-group
  runnable-list:
    - elk/elasticsearch
    - elk/kibana
    - elk/logstash
    - elk/nginx
  variables:
    elasticsearch-image-tag: 7.9.0
    elasticsearch-jvm-options: "-Xmx256m -Xms256m"
    elasticsearch-http-port: 9200
    elasticsearch-internal-port: 9300
    kibana-http-port: 5601
    kibana-image-tag: 7.9.0
    logstash-image-tag: 7.17.5
    logstash-jvm-options: "-Xmx256m -Xms256m"   
    logstash-http-port: 9600
    nginx-listen-port: 8080
    nginx-image-tag: "latest"
    kibana-server-name: "kibana.example.com"    





