namespace: elk

stack:
  defines: process-group
  runnable-list:
    - elk/elasticsearch
    - elk/kibana
    - elk/logstash
    - elk/nginx
  variables:
    elasticsearch-image-tag:
      value: 7.9.0
      type: string     
    elasticsearch-jvm-options: 
      value: "-Xmx256m -Xms256m"
      type: string     
    elasticsearch-http-port: 
      value: 9200
      type: int    
    elasticsearch-internal-port:
      value: 9300
      type: int    
    kibana-http-port:
      value: 5601
      type: int    
    kibana-image-tag:
      value: 7.9.0
      type: string  
    logstash-image-tag:
      value: 7.17.5
      type: string     
    logstash-jvm-options: 
      value: "-Xmx256m -Xms256m"
      type: string        
    logstash-http-port:
      value: 9600
      type: int    
    nginx-listen-port:
      value: 80
      type: int    
    nginx-image-tag:
      value: latest
      type: string    





