---
namespace: elk

stack:
  defines: process-group
  metadata:
    private: false
    name: elkstack
    description: |
      Elasticsearch is an open-source, distributed, RESTful search and analytics engine.

      It is built on top of the Apache Lucene library and is designed for high-speed searching, indexing, and analysis of large volumes of data in real-time.

      Elasticsearch is part of the Elastic Stack, which also includes Logstash for data collection and processing, and Kibana for data visualization and management.
    tags: visualization, logging, self hosted, cluster, monitoring, data processing pipeline
    website: https://www.elastic.co/
    source: https://github.com/elastic
    publisher: monk.io
    icon: https://images.contentstack.io/v3/assets/bltefdd0b53724fa2ce/blt549f7d977c2a88f4/5d082d34616162aa5a85707d/logo-enterprise-search-32-color.svg
  runnable-list:
    - elk/elasticsearch
    - elk/kibana
    - elk/logstash
    - elk/nginx
  variables:
    elasticsearch-image-tag:
      value: 8.15.3
      type: string
    elasticsearch-jvm-options:
      value: -Xmx256m -Xms256m
      type: string
    elasticsearch-http-port:
      value: 9200
      type: int
    elasticsearch-internal-port:
      value: 9300
      type: int
    kibana-http-port:
      value: 5601
      type: int
    kibana-image-tag:
      value: 8.15.3
      type: string
    logstash-image-tag:
      value: 8.15.3
      type: string
    logstash-jvm-options:
      value: -Xmx256m -Xms256m
      type: string
    logstash-http-port:
      value: 9600
      type: int
    nginx-listen-port:
      value: 80
      type: int
    nginx-image-tag:
      value: latest
      type: string
